GribWeatherService/urls.py
from django.urls import path

from GribWeatherService.views import get_forecast_by_lon_lat, get_observations_by_station, \
    get_stations, update_forecast_memcache

app_name = 'GribWeatherService'

urlpatterns = [
    path('forecast/<str:lon>/<str:lat>', get_forecast_by_lon_lat, name='get_forecast_by_lon_lat'),
    path('observations/<int:station_id>', get_observations_by_station, name='get_observations_by_station'),
    path('update_forecast', update_forecast_memcache, name='update_forecast_memcache'),
    path('stations', get_stations),
]

KNMIGribService/urls.py
from django.contrib import admin
from django.urls import path, include

from weather.views import IndexView

site_patterns = [
    path('admin/', admin.site.urls),
    path('api/', include('GribWeatherService.urls')),
    path('weather/', include('weather.urls')),
    path('', IndexView.as_view(), name='index')
]

urlpatterns = [
    path('knmidata/', include(site_patterns))
]

weather/urls.py
from django.urls import path

from weather.views import LocationListView, LocationView, ForecastView, ForecastListView, IndexView

app_name = 'weather'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('location/', LocationListView.as_view(), name='location_list'),
    path('location/<int:pk>', LocationView.as_view(), name='location'),
    path('forecast/', ForecastListView.as_view(), name='forecast_list'),
    path('forecast/<int:pk>', ForecastView.as_view(), name='forecast')
]

GribWeatherService/models.py
from django.contrib.gis.db.models import PointField
from django.db import models

# Create your models here.


class Location(models.Model):
    location = PointField()
    # location = models.CharField(max_length=200)  # lon/lat in string form
    station_id = models.IntegerField(blank=True, null=True)
    nearest_station_id = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=10000, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'[{self.station_id}] {self.name}'

weather/models.py
from django.db import models

# Create your models here.

GribWeatherService/views.py
import os
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.core.cache import caches

from GribWeatherService.knmi_utils import update_observations_cache, fill_forecast_cache
from GribWeatherService.models import Location
from GribWeatherService.utils import grib_data_nearest_point
from KNMIGribService.settings import NC_DATA_FOLDER, KNMI_NC_PREFIX, HARMONIE_DATA_FOLDER, \
    HARMONIE_FILENAME

NETCDF_FILENAME = 'HA40_N55_202104130000_00000_GB.nc'

TOLERANCE = 0.2


def get_stations(request):
    return JsonResponse({l.station_id: {'name': l.name,
                                        'station_id': l.station_id,
                                        'description': l.description,
                                        'location': {'lon': l.location.x,
                                                     'lat': l.location.y}}
                         for l in Location.objects.all()})


def get_observations_by_station(request, station_id):


    observations_cache = caches['observations']

    # import_locations()

    station = get_object_or_404(Location, station_id=station_id)

    # new_ncs = get_ncs()
    # if new_ncs:
    #     update_cache(new_ncs)

    print(f'{station.station_id}')

    result = []

    should_update_cache = False

    for file in sorted(os.listdir(NC_DATA_FOLDER))[-24*6:]:
        if file.startswith(KNMI_NC_PREFIX):
            wn_values = observations_cache.get(f'{station.station_id}--{file}')
            if wn_values:
                result.append(wn_values)
            else:
                print('Missing data in cache for:' + file)
                should_update_cache = True

    if should_update_cache:
        update_observations_cache()

    if not result:
        return JsonResponse(data={'success': False, 'reason': 'There is no weather data available'
                                                              'at this time.'})

    description = observations_cache.get('description') or []
    units = observations_cache.get('units') or []

    return JsonResponse(data={'success': True,
                              'data': result,
                              'station': {'name': station.name,
                                          'station_id': station.station_id,
                                          'description': station.description,
                                          'location': {'lon': station.location.x,
                                                       'lat': station.location.y}
                                          },
                              'units': units,
                              'description': description

                              }

                        )


def get_forecast_by_lon_lat(request, lon, lat):
    try:
        float_lon = float(lon)
    except (ValueError, OverflowError) as e:
        return JsonResponse(data={'success': False, 'reason': 'There was a problem converting the '
                                                              '\'lon\' argument.'})
    try:
        float_lat = float(lat)
    except (ValueError, OverflowError) as e:
        return JsonResponse(data={'success': False, 'reason': 'There was a problem converting the '
                                                              '\'lat\' argument.'})

    try:
        data = grib_data_nearest_point(float_lat, float_lon)
    except ValueError as e:
        return JsonResponse(data={'success': False, 'reason': 'The requested coordinates were out '
                                                              'of bounds for the dataset.',
                                  'exception': str(e)})

    units = {
        'dt': "s",
        'mslp': "Pa",
        'rh': "%",
        't': "C",
        'u': "m/s",
        'v': "m/s",
        'ip': "kg/m²",
        'ig': "m/s",
        'ff': "m/s",
    }
    description = {
        'dt': "Time of prediction, in UTC, Unix timestamp",
        'time': "Time of prediction, in UTC",
        'mslp': "Pressure reduced to MSL",
        'rh': "Relative humidity",
        't': "Temperature",
        'u': "u-component of wind ",
        'v': "v-component of wind",
        'ip': "Total precipitation",
        'ig': "Wind Gusts",
        'ff': "Wind speed",

    }
    return JsonResponse(data={
        'success': True,
        'data': data,
        'units': units,
        'description': description
    })


def update_forecast_memcache(request):
    grib_file = os.path.join(HARMONIE_DATA_FOLDER, HARMONIE_FILENAME)
    fill_forecast_cache(grib_file)
    print("Updated forecast cache")
    return JsonResponse(data={
        'success': True,
    })

weather/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, DetailView, ListView

from GribWeatherService.models import Location


class IndexView(TemplateView):
    template_name = 'weather/index.html'


class LocationListView(ListView):
    model = Location
    template_name = 'weather/location_list.html'


class LocationView(DetailView):
    template_name = 'weather/location.html'
    model = Location

    def get_object(self, queryset=None):
        if not queryset:
            queryset = Location.objects
        object = queryset.get(station_id=self.kwargs['pk'])
        # object.lat, object.lon = object.location.split(',')
        return object


class ForecastListView(ListView):
    model = Location
    template_name = 'weather/forecast_list.html'


class ForecastView(DetailView):

    template_name = 'weather/forecast.html'
    model = Location

    def get_object(self, queryset=None):
        if not queryset:
            queryset = Location.objects
        object = queryset.get(station_id=self.kwargs['pk'])
        # object.lat, object.lon = object.location.split(',')
        return object

weather/templates/navbar-content.html
{% block navbar_nav %}
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'weather:location_list' %}">Observations</a></li>
    <li>
        <a href="{% url 'weather:forecast_list' %}">Forecasts</a>
{#        <div class="uk-navbar-dropdown">#}
{#            <ul class="uk-nav uk-navbar-dropdown-nav">#}
{#                <li><a href="{% url 'weather:location_list' %}">Weer</a></li>#}
{#                <li class="uk-nav-divider"></li>#}
{#                <li><a href="{% url 'weather:location_list' %}">Weer</a></li>#}
{#            </ul>#}
{#        </div>#}
    </li>
{#    <li><a href="{% url 'weather:location_list' %}">Foto's</a></li>#}
{#    <li><a href="{% url 'weather:location_list' %}">Agenda</a></li>#}
{#    <li><a href="{% url 'weather:location_list' %}">Euroswiki <span uk-icon="icon: link"></span></a></li>#}
{#    <li><a href="{% url 'weather:location_list' %}">GRIB <span uk-icon="icon: link"></span></a></li>#}
{#    <li><a href="{% url 'weather:location_list' %}">Account</a></li>#}
{% endblock %}

weather/templates/weather/forecast.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/luxon.min.js' %}"></script>
    <script src="{% static 'js/chartjs-adapter-luxon.min.js' %}"></script>
    <script src="{% static 'js/chartjs-plugin-colorschemes.min.js' %}"></script>
{% endblock %}

{% block fullwidth-content %}
    <div class="uk-container uk-container-xlarge uk-padding">
        <div uk-grid>
            <div class="uk-width-1-4@m">
                <div class="uk-card uk-card-default uk-card-body uk-text-center">
                    <h1 class="uk-card-title">
                        {{ object.name }}
                    </h1>
                    <b>Location:</b>
                    <p>{{ object.location.x }}<br>{{ object.location.y }}</p>
                    <b>Description:</b>
                    <p>{{ object.description | linebreaks }}</p>

                </div>
            </div>
            <div class="uk-width-3-4@m uk-position-relative uk-height-medium">
                <canvas id="temperature-chart" class="uk-inline"></canvas>
            </div>
        </div>
    </div>

    <div class="uk-overflow-auto">
        <table id="observations"
               class="uk-table uk-table-divider uk-table-small uk-table-middle">
            <thead>
            <tr id="observations_days">
                <th></th>
            </tr>
            <tr id="observations_times">
                <th></th>
            </tr>
            </thead>
            <tbody id="observations_data">
            <tr id="observations_ta">
                <th>Temperature (C)</th>
            </tr>

            </tbody>
        </table>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script>

        let temperature_chart = null;


        $.ajax({
            type: 'GET',
            url: '{% url 'GribWeatherService:get_forecast_by_lon_lat' object.location.x object.location.y %}',
        }).then(function (msg) {
            console.log(msg)

            let day_ctr = 0
            let last_day = new Date(msg.data[0].dt * 1000)

            let observations_times = $('#observations_times')
            let observations_ta = $('#observations_ta')
            let observations_days = $('#observations_days')

            msg.data.forEach(function (timestep, index, arr) {

                let date = new Date(timestep.dt * 1000)

                let difference = Math.floor((new Date() - date) / 1000 / 60)
                let td_open_class = ''
                let difference_string = ''
                if (index + 1 === arr.length) {
                    td_open_class = 'uk-text-bold uk-alert-success uk-width-small'
                    difference_string = '<br>(' + difference + ' minutes ago)'
                }

                if (date.getDate() !== last_day.getDate() || index + 1 === arr.length) {
                    observations_days.append('<th colspan="' + day_ctr + '">' + last_day.toLocaleDateString() + '</th>')
                    day_ctr = 0
                    last_day = date

                } else day_ctr++
                observations_times.append('<th class="' + td_open_class + '">' + date.toLocaleTimeString('nl', {
                    hour: '2-digit',
                    minute: '2-digit'
                }) + difference_string + '</th>')
                observations_ta.append('<td class="' + td_open_class + '">' + timestep.ta + '</td>')

                // Update charts
                let time_str = date.toLocaleString('nl', {
                    weekday: 'short',
                    hour: '2-digit',
                    minute: '2-digit'
                })

                timestep['dt'] = timestep['dt'] * 1000
                timestep['pp'] = timestep['mslp'] / 100

            })

            let colors = Chart.colorschemes['brewer'].SetThree12

            // Update temperature chart after all data points are added
            temperature_chart = new Chart($('#temperature-chart'), {
                type: 'line',
                data: {
                    datasets: [{
                        label: msg.description['t'] + ' (' + msg.units['t'] + ')',
                        yAxisID: 'yta',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 't',
                        },
                        {#backgroundColor: '#fbb4ae',#}
                        {#borderColor: '#fbb4ae',#}
                        radius: 0,
                        hoverRadius: 3,
                    }, {
                        label: msg.description['mslp'] + ' (' + msg.units['mslp'] + ')',
                        yAxisID: 'ypp',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'mslp',
                        },
                        {#backgroundColor: '#b3cde3',#}
                        {#borderColor: '#b3cde3',#}
                        radius: 0,
                        hoverRadius: 3,
                    }, {
                        label: msg.description['ip'] + ' (' + msg.units['ip'] + ')',
                        yAxisID: 'yip',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'ip',
                        },
                        {#backgroundColor: '#b3cde3',#}
                        {#borderColor: '#b3cde3',#}
                        radius: 0,
                        hoverRadius: 3,
                    }, {
                        label: msg.description['ig'] + ' (' + msg.units['ig'] + ')',
                        yAxisID: 'yig',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'ig',
                        },
                        {#backgroundColor: '#b3cde3',#}
                        {#borderColor: '#b3cde3',#}
                        radius: 0,
                        hoverRadius: 3,
                    }, {
                        label: msg.description['ff'] + ' (' + msg.units['ff'] + ')',
                        yAxisID: 'yig',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'ff',
                        },
                        {#backgroundColor: '#b3cde3',#}
                        {#borderColor: '#b3cde3',#}
                        radius: 0,
                        hoverRadius: 3,
                    }
                    ]
                },
                defaults: {
                },
                options: {


                    plugins: {
                        colorschemes: {
                            scheme: 'brewer.SetOne5'
                        }
                    },
                    {#events: ['mousemove', 'mouseout', 'click', 'touchstart', 'touchmove'],#}
                    interaction: {
                        mode: 'index',
                        intersect: false,
                     },
                    scales: {
                        xAxis: {
                            type: 'time',
                            time: {
                                tooltipFormat: 'D TT'
                            },
                            {#ticks: {#}
                            {#    callback: function(val, index, arr) {#}
                            {#        let time_str = val.split(':')[0] + ":" + val.split(':')[1]#}
                            {#        let offset = null#}
                            {#        console.log(val)#}
                            {#        if (time_str.includes(':00')) {#}
                            {#            offset = Math.floor(parseInt(time_str.split(':')[0]))#}
                            {##}
                            {#            console.log(offset)#}
                            {#            if ((index + offset) % 4 === 0) {#}
                            {#                return time_str#}
                            {#            }#}
                            {#        } else return null#}
                            {#    }#}
                            {# }#}

                        },
                        yta: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne5[0]
                            },
                            max: 40,
                            min: -10
                        },
                        ypp: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne5[1]
                            },
                            beginAtZero: false,
                            max: 104000,
                            min: 94000,
                            grid: {
                                drawOnChartArea: false
                            }
                        },
                        yip: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne5[2]
                            },
                            beginAtZero: false,
                            {#max: 104000,#}
                            {#min: 94000,#}
                            grid: {
                                drawOnChartArea: false
                            }
                        },
                        yig: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne5[3]
                            },
                            beginAtZero: false,
                            {#max: 104000,#}
                            {#min: 94000,#}
                            grid: {
                                drawOnChartArea: false
                            }
                        }
                    },
                    animation: false,
                    // Make chart resizable
                    responsive: true,
                    maintainAspectRatio: false,
                }
            })

            console.log(temperature_chart)

        })


    </script>
{% endblock %}

weather/templates/weather/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="uk-container uk-container-xsmall">
        <a href="{% url 'weather:location_list' %}"><h1>Observations (weather stations)</h1></a>
        <a href="{% url 'weather:forecast_list' %}"><h1>Forecast (same weather stations, using Harmonie)</h1></a>
    </div>
{% endblock %}

weather/templates/weather/location.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/luxon.min.js' %}"></script>
    <script src="{% static 'js/chartjs-adapter-luxon.min.js' %}"></script>
    <script src="{% static 'js/chartjs-plugin-colorschemes.min.js' %}"></script>
{% endblock %}

{% block fullwidth-content %}
    <div class="uk-container uk-container-xlarge uk-padding">
        <div uk-grid>
            <div class="uk-width-1-4@m">
                <div class="uk-card uk-card-default uk-card-body uk-text-center">
                    <h1 class="uk-card-title">
                        {{ object.name }}
                    </h1>
                    <b>Location:</b>
                    <p>{{ object.location.x }}<br>{{ object.location.y }}</p>
                    <b>Description:</b>
                    <p>{{ object.description | linebreaks }}</p>

                </div>
            </div>
            <div class="uk-width-3-4@m">
                <ul class="uk-breadcrumb">
                    <li><a href="{% url 'weather:index' %}">Weather</a></li>
                    <li><a href="{% url 'weather:location_list' %}">Locations</a></li>
                    <li><a href="{% url 'weather:location' object.station_id %}">{{ location.name }}</a></li>
                </ul>
                <div class="uk-position-relative uk-height-medium">
                    <canvas id="temperature-chart" class="uk-inline"></canvas>
                </div>

                <div class="uk-position-relative uk-height-medium">
                    <canvas id="wind-chart" class="uk-inline"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="uk-overflow-auto">
        <table id="observations"
               class="uk-table uk-table-divider uk-table-small uk-table-middle">
            <thead>
            <tr id="observations_days">
                <th></th>
            </tr>
            <tr id="observations_times">
                <th></th>
            </tr>
            </thead>
            <tbody id="observations_data">
            <tr id="observations_ta">
                <th>Temperature (C)</th>
            </tr>

            </tbody>
        </table>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script>

        let temperature_chart = null;


        $.ajax({
            type: 'GET',
            url: '{% url 'GribWeatherService:get_observations_by_station' object.station_id %}',
        }).then(function (msg) {
            console.log(msg)

            let day_ctr = 0
            let last_day = new Date(msg.data[0].dt * 1000)

            let observations_times = $('#observations_times')
            let observations_ta = $('#observations_ta')
            let observations_days = $('#observations_days')

            let last_data_point = msg.data[msg.data.length - 1]


            let date = new Date(last_data_point.dt * 1000)

            let difference = Math.floor((new Date() - date) / 1000 / 60)
            let td_open_class = ''
            let difference_string = ''
            td_open_class = 'uk-text-bold uk-alert-success uk-width-small'
            difference_string = '<br>(' + difference + ' minutes ago)'

            observations_days.append('<th colspan="' + day_ctr + '">' + last_day.toLocaleDateString() + '</th>')


            observations_times.append('<th class="' + td_open_class + '">' + date.toLocaleTimeString('nl', {
                hour: '2-digit',
                minute: '2-digit'
            }) + difference_string + '</th>')
            observations_ta.append('<td class="' + td_open_class + '">' + last_data_point.ta + '</td>')

            // Update charts
            msg.data.forEach(function (timestep,) {
                timestep['dt'] = timestep['dt'] * 1000

            })

            let colors = Chart.colorschemes['brewer'].SetThree12

            // Update temperature chart after all data points are added
            temperature_chart = new Chart($('#temperature-chart'), {
                type: 'line',
                data: {
                    datasets: [{
                        label: msg.description['ta'],
                        yAxisID: 'yta',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'ta',
                        },
                        {#backgroundColor: '#fbb4ae',#}
                        {#borderColor: '#fbb4ae',#}
                        radius: 0,
                        hoverRadius: 3,
                    }, {
                        label: msg.description['pp'],
                        yAxisID: 'ypp',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'pp',
                        },
                        {#backgroundColor: '#b3cde3',#}
                        {#borderColor: '#b3cde3',#}
                        radius: 0,
                        hoverRadius: 3,
                    }
                    ]
                },
                defaults: {
                },
                options: {


                    plugins: {
                        colorschemes: {
                            scheme: 'brewer.SetOne3'
                        }
                    },
                    {#events: ['mousemove', 'mouseout', 'click', 'touchstart', 'touchmove'],#}
                    interaction: {
                        mode: 'index',
                        intersect: false,
                     },
                    scales: {
                        xAxis: {
                            type: 'time',
                            time: {
                                tooltipFormat: 'D TT'
                            },
                            {#ticks: {#}
                            {#    callback: function(val, index, arr) {#}
                            {#        let time_str = val.split(':')[0] + ":" + val.split(':')[1]#}
                            {#        let offset = null#}
                            {#        console.log(val)#}
                            {#        if (time_str.includes(':00')) {#}
                            {#            offset = Math.floor(parseInt(time_str.split(':')[0]))#}
                            {##}
                            {#            console.log(offset)#}
                            {#            if ((index + offset) % 4 === 0) {#}
                            {#                return time_str#}
                            {#            }#}
                            {#        } else return null#}
                            {#    }#}
                            {# }#}

                        },
                        yta: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne3[0]
                            },
                            max: 40,
                            min: -10
                        },
                        ypp: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne3[1]
                            },
                            beginAtZero: false,
                            max: 1040,
                            min: 940,
                            grid: {
                                drawOnChartArea: false
                            }
                        }
                    },
                    animation: false,
                    // Make chart resizable
                    responsive: true,
                    maintainAspectRatio: false,
                }
            })

            console.log(temperature_chart)
        // Update wind chart after all data points are added
            wind_chart = new Chart($('#wind-chart'), {
                type: 'line',
                data: {
                    datasets: [{
                        label: msg.description['ff'],
                        yAxisID: 'yff',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'ff',
                        },
                        {#backgroundColor: '#fbb4ae',#}
                        {#borderColor: '#fbb4ae',#}
                        radius: 0,
                        hoverRadius: 3,
                    }, {
                        label: msg.description['gff'],
                        yAxisID: 'yff',
                        data: msg.data,
                        parsing: {
                            xAxisKey: 'dt',
                            yAxisKey: 'gff',
                        },
                        {#backgroundColor: '#b3cde3',#}
                        {#borderColor: '#b3cde3',#}
                        radius: 0,
                        hoverRadius: 3,
                    }
                    ]
                },
                defaults: {
                },
                options: {


                    plugins: {
                        colorschemes: {
                            scheme: 'brewer.SetOne3'
                        }
                    },
                    {#events: ['mousemove', 'mouseout', 'click', 'touchstart', 'touchmove'],#}
                    interaction: {
                        mode: 'index',
                        intersect: false,
                     },
                    scales: {
                        xAxis: {
                            type: 'time',
                            time: {
                                tooltipFormat: 'D TT'
                            },
                            {#ticks: {#}
                            {#    callback: function(val, index, arr) {#}
                            {#        let time_str = val.split(':')[0] + ":" + val.split(':')[1]#}
                            {#        let offset = null#}
                            {#        console.log(val)#}
                            {#        if (time_str.includes(':00')) {#}
                            {#            offset = Math.floor(parseInt(time_str.split(':')[0]))#}
                            {##}
                            {#            console.log(offset)#}
                            {#            if ((index + offset) % 4 === 0) {#}
                            {#                return time_str#}
                            {#            }#}
                            {#        } else return null#}
                            {#    }#}
                            {# }#}

                        },
                        yff: {
                            position: 'left',
                            ticks: {
                                color: Chart.colorschemes.brewer.SetOne3[0]
                            },
                            {#max: 40,#}
                            {#min: -10#}
                        },
                    },
                    animation: false,
                    // Make chart resizable
                    responsive: true,
                    maintainAspectRatio: false,
                }
            })

            console.log(temperature_chart)

        })


    </script>
{% endblock %}